config/routes.rb
Rails.application.routes.draw do
  get 'stories/search', to: 'stories#search'

  root :to => 'users#index'

  resources :stories do
    resources :sentences
  end

  resources :users do
    resources :sentences, only: [:show]
  end
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  belongs_to :user
  belongs_to :story
  validates :text, :presence => true
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

  def index
    @story = Story.find(params[:story_id])
    @sentences = @story.sentences.all
    @user = User.find(session[:current_user_id])
  end

  def new
    @sentence = Sentence.new
    @story = Story.find(params[:story_id])
    @user = User.find(session[:current_user_id])
    number = rand($image_array.length)
    @image = $image_array[number]
    @sentences = @story.sentences.all
  end

  def create
    @story = Story.find(params[:story_id])
    @sentence = Sentence.new(sentence_params)
    puts(sentence_params)
    if @sentence.save
      redirect_to story_sentences_path(@story)
    else
      flash[:error] = "Try Again"
      render :new
    end
  end

  def edit
    @story = Story.find(params[:story_id])
    @user = User.find(session[:current_user_id])
    @sentence = Sentence.find(params[:id])
    @image = @sentence.image
  end

  def update
    @story = Story.find(params[:story_id])
    @sentence = Sentence.find(params[:id])
    if @sentence.update(sentence_params)
      redirect_to story_sentences_path(@story)
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:story_id])
    @sentence = Sentence.find(params[:id])
    @sentence.destroy
    redirect_to story_sentences_path(@story)
  end


  private
  def sentence_params
    params.require(:sentence).permit(:text, :image, :user_id, :story_id)
  end
end

app/views/sentences/_form.html.erb
<%= form_for [@story, @sentence] do |f| %>
  <%= f.label :text %>
  <%= f.text_area :text, class: "materialize-textarea" %>
  <%= f.text_field :image, type: "hidden", value: @image %>
  <%= f.text_field :user_id, type: "hidden", value: @user.id %>
  <%= f.text_field :story_id, type: "hidden", value: @story.id %>


  <%= f.submit "Add Contribution", class: "btn" %>
<% end %>

app/views/sentences/edit.html.erb
<h3>Edit You Story Contribution</h3>

<%= render 'form' %>

app/views/sentences/index.html.erb
<div class="image-container center-align">
  <br><%= image_tag(@story.image, id: "title-card") %>
  <h1> <%= @story.title %> </h1>
</div>






<div class="flex">
  <% @sentences.each do |sentence| %>

  <div class="card">
      <div class="card-image waves-effect waves-block waves-light">
        <img src='<%= sentence.image %>' alt="picture" class="activator card-image">
        <!-- <%= image_tag(sentence.image, class: "activator card-image") %> -->
        <p class="card-title">
          <%=sentence.text %>
        </p>
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4"><i class="material-icons right">more_vert</i></span>
        <p class="position">
        </p>
        <% if (sentence.user) %>
        <p>By: <%= sentence.user.name %> </p>
        <% end %>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
        <p><%= link_to "Edit", edit_story_sentence_path(@story, sentence) %> |
        <%= link_to "Delete", story_sentence_path(@story, sentence),
        :data => {:confirm => "Are you sure?",
          :method => "delete"} %></p>
      </div>
    </div>

</div>
<%end %>

<div class="center-align">
  <%= link_to "Add To This Story", new_story_sentence_path, class:"btn" %>
  <%= link_to "Back to Stories", stories_path(@user), class:"btn orange" %>
  <%= link_to "Back to Users", users_path, class:"btn red" %><br><br>
</div>

app/views/sentences/new.html.erb
<ul>
  <% @sentences.each do |sentence| %>
    <li><%=sentence.text %></li>
  <% end %>
</ul>
<%= image_tag(@image) %>

<h1>Add to the story:</h1>

<%= render 'form' %>