config/routes.rb
Rails.application.routes.draw do
  get 'stories/search', to: 'stories#search'

  root :to => 'users#index'

  resources :stories do
    resources :sentences
  end

  resources :users do
    resources :sentences, only: [:show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sentences
  has_many :stories, through: :sentences
  validates :name, :presence => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end
  def new
    @user = User.new
    render :new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      alert("try again")
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Add User", class: 'btn' %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %>:</h2>
<%=render 'form'%>

app/views/users/index.html.erb
<h3 class="center-align">Choose your login:</h3>

<% @users.each do |user| %>
<%= link_to stories_path(user) do %>
<div class="card">
  <div class="card-content center-align">
      <h2 class="black-text">
      <%= user.name %>
      </h2>
    <p class="left-align"><%= link_to "Edit", edit_user_path(user) %> | <%= link_to "Delete", user_path(user),
    :data => {:confirm => "Are you sure?",
      :method => "delete"} %></p>
  </div>
  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
    <p>Here is some more information about this product that is only revealed once clicked on.</p>
  </div>
</div>
<% end %>
<% end %>


<%= link_to "Add New User", new_user_path, class:"btn" %>

app/views/users/new.html.erb
<h2>New User:</h2>

<%= render "form" %>