config/routes.rb
Rails.application.routes.draw do
  get 'stories/search', to: 'stories#search'

  root :to => 'users#index'

  resources :stories do
    resources :sentences
  end

  resources :users do
    resources :sentences, only: [:show]
  end
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :sentences
  has_many :users, through: :sentences
  validates :title, :presence => true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def search
    @tf = true
    @stories = Story.basic_search(search_params[:search_term])

    render :index;
  end

  def index
    @tf = true
    @stories = Story.all
    if (params[:format] === nil && session[:current_user_id] === nil)
      @tf = false
    elsif (params[:format])
      session[:current_user_id] = params[:format]
    end
  end

  def new
    @story = Story.new
    number = rand($image_array.length)
    @image = $image_array[number]
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to stories_path
    else
      flash[:error] = "Try Again"
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to stories_path
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.sentences.each do |sentence|
      sentence.destroy
    end
    @story.destroy
    redirect_to stories_path
  end

  private
  def story_params
    params.require(:story).permit(:title, :image)
  end

  def search_params
    params.permit(:search_term)
  end
end

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.text_field :image, type: "hidden", value: @image %>
  <%= f.submit "Add Story", class: "btn"%>
<% end %>

app/views/stories/edit.html.erb
<h3>Edit Story</h3>

<%= render 'form' %>

app/views/stories/index.html.erb
<h1 class="center-align">Choose a Story:</h1>
<% if @tf %>
<ul>



<div class="flex">
  <% @stories.each do |story| %>
  <%= link_to story_sentences_path(story)  do %>
    <div class="card">
        <%= image_tag(story.image, width: "100%") %>
      <div class="card-stacked">
        <h4 class="black-text center-align"><%=  story.title %></h4>
        <div class="card-action">
          <%= link_to "Edit", edit_story_path(story) %>| &nbsp &nbsp <%= link_to "Delete", story_path(story),
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
          </div>
        </div>
      </div>
      <%end %>
    <%end %>
</div>






<%= link_to "Add New Story", new_story_path, class: "btn" %>
<%= link_to "Back to Users", users_path, class: "btn red" %>

<%= form_tag("/stories/search", method: 'get') do %>
  <%= label_tag(:search_term, "Search for:") %>
  <%= text_field_tag(:search_term) %>
  <%= submit_tag("Search", class: "btn")%>
<% end %>


<% else %>
<h1>Log in to view stories</h1>
<% end %>

app/views/stories/new.html.erb
<h2>New Story:</h2>
<%= image_tag(@image) %>
<%= render "form" %>